### ISSUE TITLE
Puerto serie

### ISSUE THREAD

**Issue by ernesto-g** [martinribelotta/uPyIDE#1]
Por lo menos en windows, self.widget.setPort() (linea 60) requiere un numero, el puerto que va a abrir es ese numero +1. actualmente se le esta pasando el texto del combo ("COM5" por ejemplo) y entonces explota en esa linea)

**Comment by martinribelotta** [comment]
Fijate que hice un par de cambios a ver si anda.

**Comment by martinribelotta** [comment]
Cerrado por no verse mas el error
